-- | A list of all instructions.  File generated by SetupInstrs.hs
module Language.PowerPC.Instructions (instructions) where

import Language.PowerPC.Instruction
import Language.PowerPC.Instructions.B

-- | All available instructions.
instructions :: [Instruction]
instructions =
  [ b
  ]
